DISPLAY_WIDTH = 800
DISPLAY_HEIGHT = 600
DISPLAY_SCALE = 2.5

TILE_STEP = 16

SCALED_DISPLAY_W = DISPLAY_WIDTH / DISPLAY_SCALE / TILE_STEP
SCALED_DISPLAY_H = DISPLAY_HEIGHT / DISPLAY_SCALE / TILE_STEP

FPS = 60
FONT_FILE = 'fonts/ICOIN.FON'

WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
